[features]
seeds = true
skip-lint = false

[programs.devnet]
anchor_movie_reviews_program = "3hy3VwhYp2b7BF46pij8GFvVMZ9bkjY4G7NdLXe4XeZc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/swaroopmaddu/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
